name: Deta Space Deployment Github Action
description: Github Action for deploying Deta Space apps.

branding:
  icon: upload-cloud
  color: purple

inputs:
  access_token:
    description: Deta access token for Deta Space CLI authentication.
    required: true

  project_id:
    description: Deta Space app project ID.
    required: true

  space_push:
    description: Whether to do space push. Valid value is "true". Space push will not be performed by default.
    required: false

  space_release:
    description: Whether to do space release without listing the revision on Space Discovery. Valid value is "true". Space release will not be performed by default.
    required: false

  list_on_discovery:
    description: Whether to list the latest revision on Space Discovery. Valid value is "true". Listing on Space Discovery will not be performed by default.
    required: false

  release_version:
    description: Version for the release. If not provided, Deta Space will generate a version by default.
    required: false

runs:
  using: composite

  steps:
    - name: Install Deta Space CLI & set SPACE_ACCESS_TOKEN environment variable
      shell: bash
      run: |
        curl -fsSL https://get.deta.dev/space-cli.sh | sh
        echo '/home/runner/.detaspace/bin' >> $GITHUB_PATH
        echo "SPACE_ACCESS_TOKEN=${{ inputs.access_token }}" >> $GITHUB_ENV

    - name: Push changes to Deta Space
      if: ${{ inputs.space_push == "true" }}
      shell: script -q -e -c "bash {0}"
      run: |
        space push --id "${{ inputs.project_id }}"

    - name: Create a release on Deta Space
      if: ${{ inputs.space_release == "true" }}
      shell: script -q -e -c "bash {0}"
      run: |
        if [[ ${{ inputs.list_on_discovery }} == "true" ]]; then
          space release --id "${{ inputs.project_id }}" --version "${{ inputs.release_version }}" --listed --confirm
        else
          space release --id "${{ inputs.project_id }}" --version "${{ inputs.release_version }}" --confirm
        fi
